export const FEEDBACK_REMINDER_INTERVAL_DAYS = 2;
export const FEEDBACK_SOFT_BLOCK_DAYS = 7;
export const MS_PER_DAY = 86_400_000;

export const FEEDBACK_REMINDER_INTERVAL_MS =
  FEEDBACK_REMINDER_INTERVAL_DAYS * MS_PER_DAY;
export const FEEDBACK_SOFT_BLOCK_MS = FEEDBACK_SOFT_BLOCK_DAYS * MS_PER_DAY;
